#ifndef MOLTAROS_KEYBOARD_H
#define MOLTAROS_KEYBOARD_H

#import <stdint.h>

#define KBD_PORT 0x60
#define RELEASE_MASK 0x80
#define KBD_NSCANS 0x80
#define KBD_ESCAPED_NSCANS 0xE0


/*
    A minimal keyboard driver that conforms to my laptop's keyboard layout.
*/

// Below is all character codes for the given buttons.
enum {
    KBD_KEY_ESC = 0x1, 
    KBD_KEY_F1, 
    KBD_KEY_F2, 
    KBD_KEY_F3, 
    KBD_KEY_F4, 
    KBD_KEY_F5, 
    KBD_KEY_F6,
    KBD_KEY_F7, 
    KBD_KEY_F8, 
    KBD_KEY_F9, 
    KBD_KEY_F10, 
    KBD_KEY_F11, 
    KBD_KEY_F12, 
    KBD_KEY_PRTSCR,
    KBD_KEY_SCROLL_LOCK, 
    KBD_KEY_PAUSE, 
    KBD_KEY_INSERT, 
    KBD_KEY_DELETE, 
    KBD_KEY_PAGE_UP, 
    KBD_KEY_PAGE_DOWN,
    KBD_KEY_GRAVE_ACCENT, 
    KBD_KEY_1, 
    KBD_KEY_2, 
    KBD_KEY_3, 
    KBD_KEY_4, 
    KBD_KEY_5, 
    KBD_KEY_6, 
    KBD_KEY_7, 
    KBD_KEY_8, 
    KBD_KEY_9,
    KBD_KEY_0, 
    KBD_KEY_MINUS, 
    KBD_KEY_EQUALS, 
    KBD_KEY_BACKSPACE, 
    KBD_KEY_NUMLOCK, 
    KBD_KP_KEY_SLASH, 
    KBD_KP_KEY_ASTERISK,
    KBD_KP_KEY_MINUS, 
    KBD_KEY_TAB, 
    KBD_KEY_Q, 
    KBD_KEY_W, 
    KBD_KEY_E, 
    KBD_KEY_R, 
    KBD_KEY_T, 
    KBD_KEY_Y, 
    KBD_KEY_U, 
    KBD_KEY_I, 
    KBD_KEY_O,
    KBD_KEY_P, 
    KBD_KEY_LBRACKET, 
    KBD_KEY_RBRACKET, 
    KBD_KEY_BACK_SLASH, 
    KBD_KP_KEY_7, 
    KBD_KP_KEY_8, 
    KBD_KP_KEY_9, 
    KBD_KP_KEY_PLUS,
    KBD_KEY_CAPS_LOCK, 
    KBD_KEY_A, 
    KBD_KEY_S, 
    KBD_KEY_D, 
    KBD_KEY_F, 
    KBD_KEY_G, 
    KBD_KEY_H, 
    KBD_KEY_J, 
    KBD_KEY_K, 
    KBD_KEY_L, 
    KBD_KEY_SEMICOLON,
    KBD_KEY_APOSTROPH, 
    KBD_KEY_ENTER, 
    KBD_KP_KEY_4, 
    KBD_KP_KEY_5, 
    KBD_KP_KEY_6, 
    KBD_KEY_LSHIFT, 
    KBD_KEY_Z, 
    KBD_KEY_X, 
    KBD_KEY_C,
    KBD_KEY_V, 
    KBD_KEY_B, 
    KBD_KEY_N, 
    KBD_KEY_M, 
    KBD_KEY_COMMA, 
    KBD_KEY_PERIOD, 
    KBD_KEY_SLASH, 
    KBD_KEY_RSHIFT, 
    KBD_KEY_UP, 
    KBD_KP_KEY_1,
    KBD_KP_KEY_2, 
    KBD_KP_KEY_3, 
    KBD_KP_KEY_ENTER, 
    KBD_KEY_LCTRL, 
    KBD_KEY_FN, 
    KBD_KEY_LALT, 
    KBD_KEY_SPACE, 
    KBD_KEY_BACK_SLASH2,
    KBD_KEY_RALT, 
    KBD_KEY_SUPER, 
    KBD_KEY_RCTRL, 
    KBD_KEY_LEFT, 
    KBD_KEY_DOWN, 
    KBD_KEY_RIGHT, 
    KBD_KP_KEY_0, 
    KBD_KP_KEY_PERIOD
};

void keyboard_init();

#endif /* endif MOLTAROS_KEYBOARD_H */